title: Frankline Otieno
author: GitHub User
email: franklineotieno@gmail.com
description: > # this means to ignore newlines until "baseurl:"
theme: jekyll-theme-cayman
Welcome to my page.

Incase you have any comment or compliments please reach me using below handles.

Thank you.

# social links
twitter_username: iam_frannk # DO NOT include the @ character, or else the build will fail!
github_username:  FranklineOtieno # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
